name: Approve Showcase Site

on:
  issue_comment:
    types:
      - created

jobs:
  process-approval:
    runs-on: ubuntu-latest
    if: >
      github.event.comment.body == '/approve' &&
      contains(fromJson('["OWNER", "COLLABORATOR", "MEMBER"]'),
      github.event.comment.author_association)
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Parse Issue Form
        id: parse
        uses: zentered/issue-forms-body-parser@v2.2.0

      - name: Update showcased-sites.json with the new website
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          PARSED_DATA: ${{ steps.parse.outputs.data }}
          RAW_ISSUE_BODY: ${{ github.event.issue.body }}
        run: python .github/scripts/approve_showcase.py

      - name: Commit Changes
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add resources/showcase/showcased-sites.json
          git commit -m "Approve showcase submission #${ISSUE_NUMBER}"
          git push

      - name: Close Issue and Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "✅ The site has been approved and added to the showcase."
